sudo: false

branches:
  only:
    - master

services:
  - docker

install:
- docker pull quay.io/helmpack/chart-testing:v2.4.0

script:
- ls -a
- docker run -it --rm --name ct quay.io/helmpack/chart-testing:v2.4.0 sh -c "ct lint --chart-dirs onos-config,onos,onos-topo,onos-cli,onos-gui,device-simulator --all --chart-yaml-schema helm_default_chart_schema.yml --lint-conf helm_lint_config.yaml --debug"
